local-phone-apps = AdvancedDisplay \
                   BasicDreams \
                   Bluetooth \
                   BluetoothMidiService \
                   BookmarkProvider \
                   Calendar \
                   CaptivePortalLogin \
                   CertInstaller \
                   CtsShimPrebuilt \
                   DeskClock \
                   Development \
                   DownloadProviderUi \
                   EasterEgg \
                   Email \
                   ExactCalculator \
                   Exchange2 \
                   ExtShared \
                   HTMLViewer \
                   Jelly \
                   KeyChain \
                   LatinIME \
                   LiveWallpapersPicker \
                   LockClock \
                   mcRegistry \
                   messaging \
                   NfcNci \
                   PacProcessor \
                   PhotoTable \
                   PicoTts \
                   PrintRecommendationServic \e
                   PrintSpooler \
                   Profiles \
                   Stk \
                   Terminal \
                   UserDictionaryProvider \
                   WallpaperBackup \
                   WallpaperPicker \
                   WAPPushManager \
                   webview 